"use client";
import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, ArrowRight, Check, Clock3, Fingerprint, Globe2, HelpCircle, LockKeyhole, LogOut, ShieldCheck, Trophy, X, Zap } from 'lucide-react';
import Game from './game';
import { api, retryPending } from '../lib/client';
type Row = { id:string; name:string; score:number; rank:number };
type Status = { serverNow:number; resetAt:number; weekResetAt:number; smsReady:boolean; user:{id:string;name:string}|null; attempt:{id:string;status:string;score:number|null}|null; weeklyBest:number|null };
function timeLeft(ms:number) { const s=Math.max(0,Math.floor(ms/1000)); return [Math.floor(s/3600),Math.floor(s/60)%60,s%60].map(n=>String(n).padStart(2,'0')).join(':'); }
export default function Home(){
 const [status,setStatus]=useState<Status|null>(null),[error,setError]=useState(''),[now,setNow]=useState(0),[offset,setOffset]=useState(0);
 const [view,setView]=useState('play'),[tab,setTab]=useState('today'),[auth,setAuth]=useState(false),[help,setHelp]=useState(false),[playing,setPlaying]=useState(false);
 const [board,setBoard]=useState<{rows:Row[];me:Row|null}|null>(null),[boardError,setBoardError]=useState('');
 const boardRequest=useRef(0);
 const [savedResult,setSavedResult]=useState<any>(null),[resultLoading,setResultLoading]=useState(false);
 const [sent,setSent]=useState(false),[phone,setPhone]=useState(''),[country,setCountry]=useState('+1'),[code,setCode]=useState(''),[name,setName]=useState(''),[authError,setAuthError]=useState(''),[busy,setBusy]=useState(false),[resendAt,setResendAt]=useState(0);
 async function refresh(){try{const s=await api('status');setStatus(s);setOffset(s.serverNow-Date.now());setError('');}catch(e){setError((e as Error).message);}}
 async function loadBoard(){const request=++boardRequest.current;setBoard(null);setBoardError('');try{const data=await api('leaderboard?period='+tab);if(request===boardRequest.current)setBoard(data);}catch(e){if(request===boardRequest.current)setBoardError((e as Error).message);}}
 useEffect(()=>{setNow(Date.now());refresh();},[]);
 useEffect(()=>{if(playing)return;const id=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id);},[playing]);
 useEffect(()=>{if(playing||!status?.user)return;const retry=()=>retryPending(status.user!.id).then(refresh);retry();const id=setInterval(retry,30000);window.addEventListener('online',retry);return()=>{clearInterval(id);window.removeEventListener('online',retry);};},[playing,status?.user?.id]);
 useEffect(()=>{loadBoard();},[tab,status?.user?.id,status?.attempt?.status]);
 useEffect(()=>{if(status&&now+offset>=status.resetAt)refresh();},[Math.floor(now/1000)]);
 const reset=status?.resetAt||(Math.floor(now/86400000)+1)*86400000,remaining=timeLeft(reset-now-offset);
 const number=()=>phone.startsWith('+')?phone.replace(/[\s()-]/g,''):country+phone.replace(/\D/g,'');
 async function signIn(e:React.FormEvent){e.preventDefault();setBusy(true);setAuthError('');try{if(sent){await api('auth/verify',{phone:number(),code,name});setAuth(false);setSent(false);await refresh();}else{await api('auth/send',{phone:number()});setSent(true);setResendAt(Date.now()+60000);}}catch(e){setAuthError((e as Error).message);}finally{setBusy(false);}}
 function start(){if(!status?.user){setAuth(true);return;}if(!status.attempt)setPlaying(true);}
 async function showResult(){if(!status?.attempt)return;setResultLoading(true);try{setSavedResult(await api('runs/details?id='+status.attempt.id));}catch(e){setError((e as Error).message);}finally{setResultLoading(false);}}
 useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>|void}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();Promise.resolve(context.registerTool({name:'view_leaderboard',title:'View SLIP leaderboard',description:'Open the global daily or weekly leaderboard and return verified standings.',inputSchema:{type:'object',properties:{period:{type:'string',enum:['today','week']}},required:['period'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},async execute(input:unknown){const period=(input as {period?:string})?.period;if(period!=='today'&&period!=='week')throw new Error('Choose today or week.');const data=await api('leaderboard?period='+period);setView('leaderboard');setTab(period);setBoard(data);return data;}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort();},[]);
 return <div className="app-shell">
 <header className="header"><button className="brand" onClick={()=>setView('play')} aria-label="SLIP home"><span className="brand-mark">╱</span>SLIP<span className="brand-caption">DAILY ARCADE</span></button><nav><button className={view==='play'?'active':''} onClick={()=>setView('play')}>Play</button><button className={view==='leaderboard'?'active':''} onClick={()=>setView('leaderboard')}>Leaderboard</button><button onClick={()=>setHelp(true)}>How to play <HelpCircle size={15}/></button></nav><button className="sign-in" onClick={()=>status?.user?api('auth/logout',{}).then(refresh).catch(e=>setError(e.message)):setAuth(true)}>{status?.user?<><span>{status.user.name}</span><LogOut size={15}/></>:<>Sign in <ArrowUpRight size={15}/></>}</button></header>
 <main className={'main '+(view==='leaderboard'?'board-view':'')}><div className="page-top"><div><div className="eyebrow"><span className="live-dot"/> THE DAILY CHALLENGE</div><h1>{view==='leaderboard'?'Every second counts.':'Stay in the game.'}</h1><p>{view==='leaderboard'?'The world’s best runs. Every score verified.':'One touch. One shot. Make it count.'}</p></div><div className="date-chip"><Globe2 size={15}/><span>GLOBAL ARENA<br/><strong>{new Date(now).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'})} · UTC</strong></span></div></div>
 <div className="dashboard"><aside className="left-column"><section className="attempt-card"><div className="section-label"><span>YOUR DAILY RUN</span><Zap size={17}/></div><div className="attempt-number">{status?.attempt?'0':'1'}<span>/ 1</span></div><h2>{status?.attempt?'Attempt used today':'One chance to climb.'}</h2><p>{status?.attempt?'Your next run is waiting tomorrow.':'A fresh start every day. A little longer every time.'}</p><div className="availability"><span className={status?.attempt?'muted-dot':'live-dot'}/>{status?.attempt?'You’ve used today’s attempt':status?.user?'Your attempt is available':'Verify your phone to compete'}</div><div className="reset-row"><span><Clock3 size={14}/> Next daily reset</span><strong>{remaining}</strong></div><small>{now ? new Date(reset).toLocaleTimeString([],{hour:'numeric',minute:'2-digit',timeZoneName:'short'}) : '—'} your time · midnight UTC</small></section>
 <section className="best-card"><div className="section-label"><span>YOUR WEEKLY BEST</span><Trophy size={17}/></div><strong>{status?.weeklyBest==null?'—':status.weeklyBest.toLocaleString()}<span> PTS</span></strong><p>{status?.weeklyBest==null?'Your first run sets the bar.':'Your best daily score this week.'}</p><div className="mini-week">MON <span/> TUE <span/> WED <span/> THU <span/> FRI <span/> SAT <span/> SUN</div></section><div className="fair-note"><ShieldCheck size={20}/><p>A level playing field.<br/><span>Same patterns. One run per day.<br/>Every score verified.</span></p></div></aside>
 <section className="arena-card"><div className="arena-top"><span><span className="live-dot"/> GAME 001</span><span>SURVIVAL</span></div><div className="arena-preview"><div className="arena-title">SLIP<span>KEEP YOUR TOUCH.</span></div><div className="obstacle bar b1"/><div className="obstacle circle c1"/><div className="obstacle square s1"/><div className="obstacle bar b2"/><div className="obstacle circle c2"/><div className="obstacle bar b3"/><div className="obstacle hex"/><div className="obstacle diamond"/><div className="trail"/><div className="player-marker"><span/></div><div className="preview-instruction">Find your gap.</div></div><div className="arena-action"><button className="play-button" disabled={!!status?.attempt||!!error} onClick={start}>{status?.attempt?'Today’s run complete':'Play today’s run'}<ArrowRight size={21}/></button><span><LockKeyhole size={12}/>{status?.user?'Hold to start · Dodge red, collect gold':'Phone verification required · Free to play'}</span><a className="demo-link" href="/demo">Play demo <ArrowUpRight size={14}/><small>No sign-in · Unlimited retries</small></a></div></section>
 <aside className="right-column"><section className="leaderboard-card"><div className="board-heading"><div><Trophy size={18}/><h2>Leaderboard</h2></div><span>GLOBAL</span></div><div className="tabs" role="tablist"><button role="tab" aria-selected={tab==='today'} className={tab==='today'?'selected':''} onClick={()=>setTab('today')}>Today</button><button role="tab" aria-selected={tab==='week'} className={tab==='week'?'selected':''} onClick={()=>setTab('week')}>This week</button></div><div className="board-reset"><Clock3 size={13}/> Resets in <b>{tab==='today'?remaining:timeLeft((status?.weekResetAt||reset)-now-offset)}</b></div><div className="table-head"><span>RANK / PLAYER</span><span>SCORE</span></div><div className="board-rows">{boardError?<div className="empty-board"><Globe2/><h3>Scores are unavailable</h3><p>{boardError}</p><button className="text-button" onClick={loadBoard}>Try again <ArrowRight size={14}/></button></div>:!board?<div className="empty-board"><span className="loader"/><p>Loading verified scores…</p></div>:board.rows.length?board.rows.map(row=><div className={'board-row '+(row.id===status?.user?.id?'you':'')} key={row.id}><span className="rank">{String(row.rank).padStart(2,'0')}</span><span className="avatar">{row.name.slice(0,1).toUpperCase()}</span><span className="row-name">{row.name}{row.id===status?.user?.id&&<small>YOU</small>}</span><strong>{row.score.toLocaleString()}</strong></div>):<div className="empty-board"><div className="empty-trophy"><Trophy size={30}/></div><h3>The board is wide open.</h3><p>{tab==='today'?'Be the first to put a verified score on today’s board.':'Your highest daily score earns your place this week.'}</p><span className="first-place">YOUR NAME COULD BE HERE</span></div>}</div><div className="your-rank"><span>{board?.me?'#'+board.me.rank:'—'}</span><p>{status?.user?status.user.name:'Your place is waiting'}<small>{status?.attempt?.status==='started'?'Score pending verification':status?.user?'Your verified rank appears here':'Sign in and make your mark'}</small></p><strong>{board?.me?.score.toLocaleString()||'—'}</strong></div><button className="board-link" onClick={()=>setView(view==='leaderboard'?'play':'leaderboard')}>{view==='leaderboard'?'Back to the game':'View full leaderboard'}<ArrowUpRight size={16}/></button></section><p className="board-footnote"><ShieldCheck size={13}/> Verified scores only. Equal scores share a rank.</p></aside></div>
 {error&&<div className="status-error" role="alert">{error} <button onClick={refresh}>Reconnect</button></div>}
 <section className="how-strip"><div className="how-title"><Fingerprint size={25}/><strong>Simple to play.<br/><span>Hard to put down.</span></strong></div><div><span className="step-number">01</span><p><b>Press & hold</b><span>Keep your finger on the starting circle.</span></p></div><div><span className="step-number">02</span><p><b>Find the gaps</b><span>Touch an obstacle and it’s over.</span></p></div><div><span className="step-number">03</span><p><b>Stay alive</b><span>100 points a second. Gold tokens add 250.</span></p></div></section></main>
 <footer><span><span className="footer-logo">╱ SLIP</span> A little focus goes a long way.</span><span>ONE NUMBER. ONE DAILY RUN. <span className="footer-square"/></span></footer>
 {auth&&<div className="modal-shade" onClick={()=>!busy&&setAuth(false)}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="auth-title" onClick={e=>e.stopPropagation()}><button className="close" aria-label="Close sign in" onClick={()=>setAuth(false)}><X size={20}/></button><div className="modal-icon"><Fingerprint size={30}/></div><div className="eyebrow">YOUR DAILY SHOT STARTS HERE</div><h2 id="auth-title">{sent?'Check your messages.':'Make your mark.'}</h2><p>{sent?'Enter the 6-digit code we sent to your phone.':'Verify your phone to claim one competitive run each day.'}</p><form onSubmit={signIn}>{!sent?<><label>Country calling code<select value={country} onChange={e=>setCountry(e.target.value)}><option value="+1">+1 · United States / Canada</option><option value="+44">+44 · United Kingdom</option><option value="+61">+61 · Australia</option><option value="+91">+91 · India</option><option value="+49">+49 · Germany</option><option value="+33">+33 · France</option><option value="+81">+81 · Japan</option><option value="+55">+55 · Brazil</option></select></label><label>Phone number<input autoFocus type="tel" autoComplete="tel" placeholder="(555) 000-0000" value={phone} onChange={e=>setPhone(e.target.value)} required/></label><small>Or enter any full international number beginning with +.</small></>:<><label>Verification code<input autoFocus inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} placeholder="000000" className="code-input" value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} required/></label><label>Public display name<input maxLength={20} minLength={3} placeholder="Choose your arcade name" value={name} onChange={e=>setName(e.target.value)} required/></label></>}{authError&&<p className="form-error" role="alert">{authError}</p>}<button className="play-button" disabled={busy}>{busy?'Connecting…':sent?'Verify & continue':'Send verification code'}<ArrowRight size={18}/></button></form>{sent&&<button className="text-button" disabled={now<resendAt||busy} onClick={async()=>{setBusy(true);try{await api('auth/send',{phone:number()});setResendAt(Date.now()+60000);}catch(e){setAuthError((e as Error).message);}setBusy(false);}}>{now<resendAt?'Resend in '+Math.ceil((resendAt-now)/1000)+'s':'Resend code'}</button>}<div className="privacy-note"><ShieldCheck size={16}/><p>Your number stays private. Only your display name is public. Verification limits runs per number, not per person.</p></div></section></div>}
 {help&&<div className="modal-shade" onClick={()=>setHelp(false)}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="help-title" onClick={e=>e.stopPropagation()}><button className="close" aria-label="Close instructions" onClick={()=>setHelp(false)}><X/></button><div className="modal-icon"><Fingerprint size={30}/></div><h2 id="help-title">Keep your touch.</h2><p>Hold the starting circle through the countdown, then drag your finger to dodge the falling shapes.</p><ul className="rules"><li><Check/> Only the small inner circle is your hitbox.</li><li><X/> Touch an obstacle or lift your finger: run over.</li><li><Clock3/> 100 points per second, plus 250 per gold token.</li><li><ShieldCheck/> Release during the countdown to cancel for free.</li></ul><p>Once authorized, your daily attempt is used. Leaving or backgrounding the game ends your run. If your connection drops, your score waits for verification.</p><button className="play-button" onClick={()=>setHelp(false)}>Got it <Check size={18}/></button></section></div>}
 {status?.attempt&&!playing&&<button className="saved-result-button" onClick={showResult} disabled={resultLoading}>{resultLoading?'Loading result…':'View today’s result'} <ArrowUpRight size={16}/></button>}
 {savedResult&&<div className="modal-shade"><section className="modal result-modal" role="dialog" aria-modal="true" aria-labelledby="saved-result-title"><button className="close" aria-label="Close result" onClick={()=>setSavedResult(null)}><X size={20}/></button><div className="eyebrow">{savedResult.run.day} · DAILY RUN</div><h2 id="saved-result-title">Your result.</h2><div className="result-score">{savedResult.run.score?.toLocaleString()??'—'}<span>POINTS</span></div><div className="verification"><ShieldCheck size={16}/>{savedResult.run.status==='verified'?'Score verified':savedResult.run.status==='started'?'Score pending verification':savedResult.run.status==='expired'?'Run ended without a verified score':'Score could not be verified'}</div><div className="result-stats"><div><span>Today’s rank</span><strong>{savedResult.daily?'#'+savedResult.daily.rank:'—'}</strong></div><div><span>Weekly best</span><strong>{savedResult.weekly?.score.toLocaleString()??'—'}</strong></div><div><span>Weekly rank</span><strong>{savedResult.weekly?'#'+savedResult.weekly.rank:'—'}</strong></div></div><p className="used-message">You’ve used today’s attempt.</p><div className="result-reset"><Clock3 size={15}/> Next attempt in <strong>{remaining}</strong></div><button className="play-button" onClick={()=>{setSavedResult(null);setView('leaderboard');}}>View leaderboard <Trophy size={18}/></button></section></div>}
 {playing&&<Game onClose={()=>{setPlaying(false);refresh();loadBoard();}} onLeaderboard={()=>{setPlaying(false);setView('leaderboard');refresh();loadBoard();}} resetAt={reset} userId={status?.user?.id||''}/>}
 </div>;
}
