import { env } from 'cloudflare:workers';
import { GAME, MAX_TICKS, HZ } from './engine';
export const settings=()=>env as unknown as Record<string,string>;
export function db(){if(!env.DB)throw new HttpError('Scores are temporarily unavailable. Please try again.',503);return env.DB;}
export class HttpError extends Error{constructor(message:string,public status=400){super(message);}}
export function ready(){const e=settings();return !!(e.TWILIO_ACCOUNT_SID&&e.TWILIO_AUTH_TOKEN&&e.TWILIO_VERIFY_SERVICE_SID&&e.PHONE_HASH_SECRET);}
export async function digest(value:string){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('');}
export async function privateKey(value:string){const secret=settings().PHONE_HASH_SECRET;if(!secret)throw new HttpError('Phone verification is not connected yet. Please check back soon.',503);const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return [...new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(value)))].map(x=>x.toString(16).padStart(2,'0')).join('');}
export function phone(value:unknown){if(typeof value!=='string'||!/^\+[1-9]\d{7,14}$/.test(value))throw new HttpError('Enter a valid phone number including its country code.');return value;}
export async function user(request:Request){const token=request.headers.get('cookie')?.match(/(?:^|;\s*)slip_session=([a-f0-9]{64})(?:;|$)/)?.[1];if(!token)return null;return await db().prepare('SELECT p.id,p.name FROM sessions s JOIN players p ON p.id=s.user_id WHERE s.token_hash=? AND s.expires_at>?').bind(await digest(token),Date.now()).first<{id:string;name:string}>();}
export async function requireUser(request:Request){const u=await user(request);if(!u)throw new HttpError('Sign in with your verified phone number to continue.',401);return u;}
export async function rate(key:string,max:number,windowMs:number){const now=Date.now();const row=await db().prepare('INSERT INTO rate_limits (key,count,expires_at) VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN expires_at<=? THEN 1 ELSE count+1 END,expires_at=CASE WHEN expires_at<=? THEN excluded.expires_at ELSE expires_at END RETURNING count').bind(key,now+windowMs,now,now).first<{count:number}>();if(!row||row.count>max)throw new HttpError('Too many requests. Please wait and try again.',429);}
export async function twilio(action:string,fields:Record<string,string>){if(!ready())throw new HttpError('Phone verification is not connected yet. Please check back soon.',503);const e=settings();const r=await fetch('https://verify.twilio.com/v2/Services/'+encodeURIComponent(e.TWILIO_VERIFY_SERVICE_SID)+'/'+action,{method:'POST',headers:{Authorization:'Basic '+btoa(e.TWILIO_ACCOUNT_SID+':'+e.TWILIO_AUTH_TOKEN),'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(fields)});const data=await r.json() as {status:string;sid:string;to:string;code?:number};if(!r.ok){if(r.status===429)throw new HttpError('Too many verification attempts. Please wait a few minutes.',429);if(data.code===20404)throw new HttpError('This code has expired. Request a new one.');if(data.code===60200||data.code===21211)throw new HttpError('Check the country code and phone number.');throw new HttpError('We couldn’t verify this request. Check your details and try again.',400);}return data;}
export function json(data:unknown,status=200,headers:Record<string,string>={}){return Response.json(data,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff',...headers}});}
export async function handle(request:Request,fn:()=>Promise<Response>){try{if(request.method==='POST'){const origin=request.headers.get('origin');if(origin&&origin!==new URL(request.url).origin)throw new HttpError('Request origin is not allowed.',403);if(!request.headers.get('content-type')?.includes('application/json'))throw new HttpError('JSON is required.',415);}return await fn();}catch(e){if(e instanceof HttpError)return json({error:e.message},e.status);console.error('API failure',e instanceof Error?e.message:'unknown');return json({error:'Unable to connect right now. Please try again.'},503);}}
export async function body(request:Request,max=600000){const text=await request.text();if(text.length>max)throw new HttpError('Request is too large.',413);try{return JSON.parse(text);}catch{throw new HttpError('Invalid request.');}}
// A ten-minute run cap and a 24-hour retry window bound standings finalization.
export const RUN_MS=MAX_TICKS/HZ*1000, RETRY_MS=86400000;
export async function finalize(){const now=Date.now(),d=db();await d.prepare("UPDATE runs SET status='expired',end_reason='interrupted' WHERE status='started' AND submit_by<?").bind(now).run();const pending=await d.prepare('SELECT id,kind,period_key FROM periods WHERE finalized_at IS NULL AND finalize_after<? LIMIT 16').bind(now).all<{id:string;kind:string;period_key:string}>();for(const p of pending.results){const col=p.kind==='today'?'day':'week';await d.batch([d.prepare(`INSERT OR IGNORE INTO standings (period_id,user_id,name,score,rank,run_id) SELECT ?,user_id,display_name,score,RANK() OVER (ORDER BY score DESC),id FROM (SELECT *,ROW_NUMBER() OVER(PARTITION BY user_id ORDER BY score DESC,started_at ASC,id ASC) n FROM runs WHERE game=? AND ${col}=? AND status='verified') WHERE n=1`).bind(p.id,GAME,p.period_key),d.prepare('UPDATE periods SET finalized_at=? WHERE id=? AND finalized_at IS NULL').bind(now,p.id)]);}}
export async function ranking(period:string,key:string,userId:string|null){const col=period==='today'?'day':'week';const sql=`WITH best AS (SELECT user_id,display_name,score,ROW_NUMBER() OVER(PARTITION BY user_id ORDER BY score DESC,started_at ASC,id ASC) n FROM runs WHERE game=? AND ${col}=? AND status='verified'),ranked AS (SELECT user_id id,display_name name,score,RANK() OVER(ORDER BY score DESC) rank FROM best WHERE n=1) SELECT * FROM ranked`;const [rows,me]=await Promise.all([db().prepare(sql+' ORDER BY score DESC,id LIMIT 50').bind(GAME,key).all(),userId?db().prepare(sql+' WHERE id=?').bind(GAME,key,userId).first():Promise.resolve(null)]);return {rows:rows.results,me};}
